### PR TITLE
Add new options "After last login" and "After completion of activity"

### PR DESCRIPTION
**Pull request by sh-csg**
This PR adds two new types of relative dates:
- After last login (to course)
- After completion of activity 

Function completion_value_used reuses code from availability_completion

### CODE REVIEW

**Comment by sh-csg** [comment]
Hi @ewallah ,

thanks for considering my pull request!

1. The value of lastcourseaccess should be constant during session (e.g. it is used in format_grid or in my branch of format_tiles for highlighting sections with new activities since last login). 

2. I am quite unexperienced in writing behat tests til now - but I'll try to write one for that scenario! But I don't see big problems in comparison to availability_completion (it seems to me as there is already some caching implemented as I had to add the completion_value_used() function for this to work without cache purging). I recently wrote an activity plugin (https://github.com/mebis-lp/mod_learningmap) which is largely dependent on activity completion and see no performance problems there. 

3. The way negation is handled right now seems to fit exactly what I purposed to happen: Negation of "five days after last login" will be "less than five days after last login" (analogous for "after completion").

The idea for this PR originated in a weekly meeting of german speaking moodle users: For "after last visit" the trainer wanted to display different messages / activities to the users who visit the course frequently / sporadical. The use case for "after completion" comes from a trainer of our central institute for further training of teachers where they host a large amount of self-study courses. They wanted to introduce some kind of delay for automatic display of dependent activities.

**Comment by ewallah** [comment]
Hi @sh-csg,

FIrst the "After last login (to course)" part:

What would happen if a user is restricted to 5 hours "after last login to course"?  If the global session timeout is 4 hours, the user would be automatically logged out and he/she has to start waiting again? What happens if the user checks the Moodle Mobile App during this waiting period? What happens if a user accesses the course, sees that he/she has to wait, browses 3 hours in other courses, and comes back to the course?

Also the definition "last login to course" seems not correct to me. I want to avoid that I have to explain again and again what this rule exactly means. As far as I can see, "after current course access" is more accurate.

Last but not least, an admin can hide the lastaccess field on site level,  so somewhere the !isset($hiddenfields['lastaccess']) function should be used to honor this decision. 

But I still not see a lot of use cases for this restriction.  Can you help me out and provide some samples?

R

**Comment by sh-csg** [comment]
Hi @ewallah ,

the value under $USER->lastcourseaccess[$courseid] remains constant during a session. Neither using the moodle app nor opening the course in a separate session nor visiting the course twice in the same session will modify this value. I will try to figure out whether limiting lastaccess also affects last course access!

The main use case should be displaying messages or some activities for users who did not visit the course for a longer time.

Two examples: 
- Label: "You didn't visit the course for the last two weeks. Please review the vocabulary in Section 2 and..."
- Quiz for checking knowledge from the "missed" time

But I agree that it may not be the most important use case ;-)

**Comment by ewallah** [comment]
Hello @sh-csg,

First, THX for fixing some code.  But I still have some problem:  the private function calc should not use the global $USER but the $userid (reports can query if the module is available or not for other users). If you use the global $USER, there reports will generate for everybody the same result.

Can you camelCase activityselector into activitySelector in the forms.js file, this will reduce the amount of lint errors (https://github.com/ewallah/moodle-availability_relativedate/runs/5733044116?check_suite_focus=true#step:14:23)

During the weekend I will try to write some tests to see if it actually works. 

R

**Comment by sh-csg** [comment]
Hi @ewallah ,
I added the changes (also for satisfying lint). I tried to keep the $USER object if its id is identical to $userid (to keep the lastcourseaccess values).
Thanks a lot for your time!
Stefan

**Comment by ewallah** [comment]
Hello @sh-csg,

Let's talk about your second addition:
- The [completion_value_used](https://github.com/moodle/moodle/blob/master/availability/classes/condition.php#L257) function is missing.  If the plugin has been configured to rely on a particular activity's completion value, it should return true. (This is necessary so that the course page can be updated when that activity becomes complete.)
- The functions calc and get_debug_string do not check if the module was deleted or not.
- Perhaps, there should be an observer class that monitors the deletion of modules. When a module is removed a course, it cannot be part of a availability restriction.  Any idea how complex restriction sets should be handled?  
- I created a basic Behat script to check if there is performance loss. I will upload it in a dev branch soon.
- The module selector in the form should only be visible when the 'After completion of activity' is selected, otherwise it should be hidden.

R

**Comment by sh-csg** [comment]
Hi @ewallah ,
* completion_value_used was added in Commit 5b8ef5a 
* both functions now check for existence of the linked course module, including a "missing module" string shown if module doesn't exist
* an observer for the event course_module_deleted is registered and updates the conditions by setting the id of the course module to -1 (this may be better than deleting the condition)
* the activity selector is now hidden by default
Best regards
Stefan

**Comment by ewallah** [comment]
Hello @sh-csg,

It was a vague sign that the code was not working out of the box in PHPUnit and Behat:
- code coverage still shows code that is never reached
- Behat output showed that the calculations always returned 0.

But adding running cron jobs in the background and login twice (it seems that the global $USER variable is only populated in the second login) brought improvement.

The code for relativestart eq 5 now seems to be working in every situation (teachers see the condition and students see a date) relative to the last login.

The code for relativestart eq 6 is still not working like it should (the calculation always returns 0 in Behat and PHPUnit).

R

**Pull request merged**
